public class CreateCon {
        Public Static Void CreateNewCon(){
        Contact con = new Contact();
        con.LastName = 'test acc';
        con.Phone = '8989898989';
        con.Email = 'test@test.com';
        insert con;
    }
     Public Static Void CreateNewAcc(){
        Account acc = new account();
        acc.name = 'test acc';
        acc.Phone = '8989898989';
        acc.Website = 'www.google.com';
        insert acc;
    }


}